### ISSUE TITLE
RLlibEnv: `ModuleNotFoundError: No module named 'python_griddly'`

### ISSUE THREAD

**Issue by joshrule** [Bam4d/Griddly#126]
**Describe the bug**
When trying to train an RLlib Trainer on a Griddly environment, ray crashes.

**To Reproduce**
1. run `python learn.py`

**Expected behavior**
I expected the model to train, but it is instead complaining that the `griddly_python` module cannot be found.

**Screenshots**
Not exactly screenshots, but here's the relevant code and output:

Code:
```python
import os
import sys

import ray
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer
from ray.rllib.models import ModelCatalog
from ray.tune.registry import register_env

from griddly import gd
from griddly.util.rllib.torch import GAPAgent
from griddly.util.rllib.environment.core import RLlibEnv

if __name__ == '__main__':

    ray.init(num_cpus=8)

    env_name = "ray-griddly-env"

    register_env(env_name, RLlibEnv)
    ModelCatalog.register_custom_model("GAP", GAPAgent)

    max_training_steps = 1000

    config = {
        'framework': 'torch',
        'num_workers': 2,
        'num_envs_per_worker': 4,

        'model': {
            'custom_model': 'GAP',
            'custom_model_config': {}
        },
        'env': env_name,
        'env_config': {
            'record_video_config': {
                'frequency': 100
            },

            'random_level_on_reset': True,
            'yaml_file': 'Single-Player/Mini-Grid/minigrid-doggo.yaml',
            'global_observer_type': gd.ObserverType.SPRITE_2D,
            'max_steps': 1000,
        },
        'entropy_coeff_schedule': [
            [0, 0.01],
            [max_training_steps, 0.0]
        ],
        'lr_schedule': [
            [0, 0.0005],
            [max_training_steps, 0.0]
        ]
    }

    stop = {
        "timesteps_total": max_training_steps,
    }

    result = tune.run(PPOTrainer, config=config, stop=stop)
```

Output:
```
$ python learn.py
/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/_private/services.py:238: UserWarning: Not all Ray Dashboard dependencies were found. To use the dashboard please install Ray using `pip install ray[default]`. To disable this message, set RAY_DISABLE_IMPORT_WARNING env var to '1'.
  warnings.warn(warning_message)
== Status ==
Memory usage on this node: 3.7/31.1 GiB
Using FIFO scheduling algorithm.
Resources requested: 3.0/8 CPUs, 0/0 GPUs, 0.0/17.64 GiB heap, 0.0/8.82 GiB objects
Result logdir: /home/rule/ray_results/PPO_2021-08-31_13-19-23
Number of trials: 1/1 (1 RUNNING)
+---------------------------------+----------+-------+
| Trial name                      | status   | loc   |
|---------------------------------+----------+-------|
| PPO_ray-griddly-env_f812d_00000 | RUNNING  |       |
+---------------------------------+----------+-------+


2021-08-31 13:19:25,076	ERROR trial_runner.py:773 -- Trial PPO_ray-griddly-env_f812d_00000: Error processing event.
Traceback (most recent call last):
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/tune/trial_runner.py", line 739, in _process_trial
    results = self.trial_executor.fetch_result(trial)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/tune/ray_trial_executor.py", line 746, in fetch_result
    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 82, in wrapper
    return func(*args, **kwargs)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/worker.py", line 1623, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=35587, ip=10.63.143.152)
  Some of the input arguments for this task could not be computed:
ray.exceptions.RaySystemError: System error: No module named 'python_griddly'
traceback: Traceback (most recent call last):
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 254, in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 190, in _deserialize_object
    return self._deserialize_msgpack_data(data, metadata_fields)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
    python_objects = self._deserialize_pickle5_data(pickle5_data)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 158, in _deserialize_pickle5_data
    obj = pickle.loads(in_band)
ModuleNotFoundError: No module named 'python_griddly'
Result for PPO_ray-griddly-env_f812d_00000:
  {}

== Status ==
Memory usage on this node: 3.8/31.1 GiB
Using FIFO scheduling algorithm.
Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/17.64 GiB heap, 0.0/8.82 GiB objects
Result logdir: /home/rule/ray_results/PPO_2021-08-31_13-19-23
Number of trials: 1/1 (1 ERROR)
+---------------------------------+----------+-------+
| Trial name                      | status   | loc   |
|---------------------------------+----------+-------|
| PPO_ray-griddly-env_f812d_00000 | ERROR    |       |
+---------------------------------+----------+-------+
Number of errored trials: 1
+---------------------------------+--------------+----------------------------------------------------------------------------------------------------------------+
| Trial name                      |   # failures | error file                                                                                                     |
|---------------------------------+--------------+----------------------------------------------------------------------------------------------------------------|
| PPO_ray-griddly-env_f812d_00000 |            1 | /home/rule/ray_results/PPO_2021-08-31_13-19-23/PPO_ray-griddly-env_f812d_00000_0_2021-08-31_13-19-24/error.txt |
+---------------------------------+--------------+----------------------------------------------------------------------------------------------------------------+

(pid=35587) 2021-08-31 13:19:25,074	ERROR serialization.py:256 -- No module named 'python_griddly'
(pid=35587) Traceback (most recent call last):
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 254, in deserialize_objects
(pid=35587)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=35587)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
(pid=35587)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 158, in _deserialize_pickle5_data
(pid=35587)     obj = pickle.loads(in_band)
(pid=35587) ModuleNotFoundError: No module named 'python_griddly'
(pid=35587) 2021-08-31 13:19:25,074	ERROR worker.py:428 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::PPO.__init__() (pid=35587, ip=10.63.143.152)
(pid=35587)   Some of the input arguments for this task could not be computed:
(pid=35587) ray.exceptions.RaySystemError: System error: No module named 'python_griddly'
(pid=35587) traceback: Traceback (most recent call last):
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 254, in deserialize_objects
(pid=35587)     obj = self._deserialize_object(data, metadata, object_ref)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 190, in _deserialize_object
(pid=35587)     return self._deserialize_msgpack_data(data, metadata_fields)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 168, in _deserialize_msgpack_data
(pid=35587)     python_objects = self._deserialize_pickle5_data(pickle5_data)
(pid=35587)   File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/serialization.py", line 158, in _deserialize_pickle5_data
(pid=35587)     obj = pickle.loads(in_band)
(pid=35587) ModuleNotFoundError: No module named 'python_griddly'
Traceback (most recent call last):
  File "learn.py", line 59, in <module>
    result = tune.run(PPOTrainer, config=config, stop=stop)
  File "/home/rule/inbox/venv38/lib/python3.8/site-packages/ray/tune/tune.py", line 555, in run
    raise TuneError("Trials did not complete", incomplete_trials)
ray.tune.error.TuneError: ('Trials did not complete', [PPO_ray-griddly-env_f812d_00000])
```

**Desktop (please complete the following information):**
 - OS: linux (NixOS)
 - Version 1.2.6
 - Relevant package versions:
    ```
    Package                    Version
    -------------------------- ------------
    griddly                    1.2.6
    gym                        0.19.0
    ray                        1.6.0
    redis                      3.5.3
    torch                      1.8.1
    ```

**Additional context**
I'm running this inside a `nix` shell, which sometimes has problems in setting up the right environment variables, particularly `PATH`-like variables. Could this simply be an issue of setting the right paths?

**Comment by joshrule** [comment]
Just to confirm that ray and RLlib are properly installed, I tried the following, which runs without incident:

```python
# ray_test.py
from ray import tune
from ray.rllib.agents.dqn import DQNTrainer

config = {
    "env": "CartPole-v0",
    "num_workers": 3,
    "framework": "torch",
}
stop = {
    "training_iteration": 100,
}

tune.run(DQNTrainer, config=config, checkpoint_freq=10)
```

**Comment by Bam4d** [comment]
Hi @joshrule.

Thanks for the question.

I've had issues with paths like this using ray + griddly + linux and to solve this you have to get ray to set the PYTHONPATH variable on it's remote workers also using the following snippet of code:

```
if __name__ == '__main__':

    #######################
    sep = os.pathsep
    os.environ['PYTHONPATH'] = sep.join(sys.path)
    #######################

    ray.init(num_cpus=8)

    env_name = "ray-griddly-env"

    register_env(env_name, RLlibEnv)
    ModelCatalog.register_custom_model("GAP", GAPAgent)

    max_training_steps = 1000

```

Let me know if this helps!

**Comment by joshrule** [comment]
That solved it for me! I suspected it had something to do with `PYTHONPATH`, but I wouldn't have thought to add all of `PATH` to `PYTHONPATH` like that. Thanks!
