### ISSUE TITLE
"Uncaught TypeError: Cannot read properties of undefined (reading 'steps')"

### ISSUE THREAD

**Issue by cool-RR** [Bam4d/Griddly#244]
I loaded a Sokoban game in griddly.ai and modified the rules a bit. I pressed "play" though I think the button was inactive. Nothing happened, but I got this in the error log:

```
HumanPlayerScene.js:594 Uncaught TypeError: Cannot read properties of undefined (reading 'steps')
    at t.processTrajectory (HumanPlayerScene.js:594:38)
    at t.update (HumanPlayerScene.js:734:16)
    at initialize.step (phaser.js:49068:26)
    at initialize.update (phaser.js:100289:21)
    at initialize.step (phaser.js:162805:20)
    at initialize.step (phaser.js:89366:14)
    at e (phaser.js:89613:19)
t.processTrajectory @ HumanPlayerScene.js:594
t.update @ HumanPlayerScene.js:734
step @ phaser.js:49068
update @ phaser.js:100289
step @ phaser.js:162805
step @ phaser.js:89366
e @ phaser.js:89613
requestAnimationFrame (async)
```

I cut off the traceback because it's long and repititive, find the full traceback in the log: https://gist.github.com/cool-RR/97a4d6043ef2c63fd119619dbb5ac568

**Comment by Bam4d** [comment]
Thanks for this bug report! Its easy to reproduce so good catch :D

I'm currently in the process of separating the GriddlyJS components into NPM modules which can be used anywhere... These will be in a separate repository so I can track the bugs better.

**Comment by cool-RR** [comment]
Hmm, my two cents (with much less background than you about this project) is that it'll be better to keep them in the same repo. Modularity is less important than the dependency hell you could get yourself into by separating to two repos. But let's discuss that  in video.
